owner: XokoukioX # GitHub username
repo: KeepServiceAlive # GitHub repository name
sites: # List of endpoints to track
  - name: QSign
    url: https://qsign-shirasuazusa.koyeb.app/
  - name: GPT_API
    url: https://go-chatgpt-api-zyw8.onrender.com
  - name: Zymooll's Services
    url: ${{secrets.ZYM}}
  - name: Blog
    url: https://www.kawakaze.dynv6.net/
assignees: # Users to assign downtime issues (optional)
  - Kawakaze
  - XokoukioX
status-website:
  baseUrl: /KeepServiceAlive # where "repo" is your repository name
  name: Kawakaze's Status Website
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
