owner: XokoukioX # GitHub username
repo: UpTimeRobot # GitHub repository name
sites: # List of endpoints to track
  - name: QSign
    url: https://qsign-shirasuazusa.koyeb.app/
  - name: CloudDrive
    url: http://zymooll.tpddns.cn:5212/login
  - name: Blog
    url: https://www.kawakaze.dynv6.net/
assignees: # Users to assign downtime issues (optional)
  - Kawakaze
  - XokoukioX
status-website:
  baseUrl: /UptimeRobot # where "repo" is your repository name
  name: Kawakaze's Status Website
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
